---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  commands:
  - docker build .


  when:
    branch:
    - master
    event:
    - push
    - pull-request
    
trigger:
  branch:
  - master
