---
kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
  - docker build .

  when:
    branch:
    - master
    event:
    - push
    - pull-request

trigger:
  branch:
  - master
