---
kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
  - docker build .
  volumes:
  - name: docker
    path: /var/run/docker.sock

  when:
    branch:
    - master
    event:
    - push
    - pull-request
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
    
trigger:
  branch:
  - master
